### ISSUE TITLE
Can't run Osiris Launcher, this is probably the wrong place to post this

### ISSUE THREAD

**Issue by paullllllll** [Wunkolo/Thoth#2]
Hello,

When I run Osiris it fails to inject the osiris dll into PID 0. If there is a better way to make contact with whoever is behind this project let me know :)

![image](https://cloud.githubusercontent.com/assets/5897580/18458166/86f5501c-7924-11e6-8373-85211850a255.png)

**Comment by Wunkolo** [comment]
"`Sep 10 2016`" this seems to be an older build of the Osiris launcher despite the name of your folder saying `12thSeptember`. Try a [newer build](https://transfer.sh/12Vke7/osiris-launcher.exe) or compiling from source.
