### ISSUE TITLE
Halo closes immediately after injection

### ISSUE THREAD

**Issue by maximumgame** [Wunkolo/Thoth#4]
Placing a break point at the end of Osiris Launcher gives the output that it succeeded in its injection. 

No log file exists in \AppData\Local\Packages\Microsoft.Halo5Forge_8wekyb3d8bbwe\LocalState

OsirisLauncher starts halo 5 forge but closes a few seconds later. The halo app opens afterwards.

**Comment by Wunkolo** [comment]
"`The halo app opens afterwards.`" Do you mean the halo hub application? Having this application installed has been known to add a layer of complexity to getting the injector to run the game properly so it's recommended to remove this application to get Halo 5: Forge to launch properly.

**Comment by maximumgame** [comment]
That was the issue. Thank you.
