### ISSUE TITLE
Vehicles (Spirit) crashes the game

### ISSUE THREAD

**Issue by HDHerrera** [Wunkolo/Thoth#6]
Hi, I saw the vehicles list...
I used cheat engine and spawned a Really Hog with a frag grenade and it did work (I followed the biped tutorial but I changed the bipeds to vehicles).
Then I tried with the Spirit and it crashed, it does the same to some of the AR Projectiles (Thanks to you now I know how to change the projectiles but some don't work (crash), like the Red Missile and the Blue missile)
Is there a solution? Am I doing something wrong?

See y'all

Edit: there it is an image and a video
![d0e88d3a-0527-489d-aa13-53bc53ca06c2](https://cloud.githubusercontent.com/assets/22239858/18607994/0b9a4e42-7cdd-11e6-88c0-90a8d2fe1dde.jpg)

http://xboxdvr.com/gamer/Halo5ForgeMod/video/21603778

**Comment by Wunkolo** [comment]
The issues platform is intended to be used for issues relating to the Osiris software and not to the tutorials on the wiki.
For help related to the tutorials try talking in the [Discord](https://discord.gg/tGR6Ajk)
