### ISSUE TITLE
Can't Get File Dump

### ISSUE THREAD

**Issue by ManApart** [Wunkolo/Thoth#8]
Not an issue with Osiris, but not sure where else to put this.

I'd like to unpack the sound files etc (.pck).

I've taken ownership of the windowsapp folder every way I can and it succeeds every time. However, no matter what, I can't copy files out of the windowsapp/forge folder.

Things like the five tool do not work because they can't get access.

When I attempt to move a file it says I need to get permission from myself. Even after I have taken ownership and the file says I am the owner.

Can anyone help me?

**Comment by Wunkolo** [comment]
Are you trying to dump the game? It seems like you want access to the games encrypted file system. [I have an entirely separate tool for this](https://github.com/Wunkolo/UWPDumper).

**Comment by ManApart** [comment]
Thanks for the response Wunkolo!

This is all a bit over my head. I'm specifically trying to get at the sound .pck files under
C:\Program Files\WindowsApps\Microsoft.Halo5Forge_1.131.5612.2_x64__8wekyb3d8bbwe\sound\win

When I try to copy them to another folder so that I can decompress them (with wwise)  I get the file permission error. Specifically:
"You need permission to perform this action. You require permission from <myself> to make chagnes to this file". And their is a lock icon over the file icon.

I ran your tool while Forge was up and got some files, but did not find the sound packs in the dump location.


NEvermind: Looks like I just needed to refresh the folder after going into a level. This is awesome. Thank you very much!

**Comment by Wunkolo** [comment]
Yea, it's dumping the entire game serially so you'll have to wait a bit for it to fully populate the DUMP folder. Glad you got it fixed.

**Comment by ManApart** [comment]
That makes sense.
It's awesome going through and hearing the announcers. Again, many thanks on your help!
